definitions:
  steps:
    - step: &set-environment
        name: Set environment
        script:
          - export > .env-ci-cd
          - cat .env-ci-cd
        artifacts:
          - .env-ci-cd
    - step: &build-app
        name: Build app
        image: node:14
        script:
          - source .env-ci-cd
          - npm i
          - npm run build
        artifacts:
          - dist/**
    - step: &deploy-scp
        name: Deploy via SCP
        script:
          - source .env-ci-cd
          - pipe: atlassian/scp-deploy:1.0.0
            variables:
              SERVER: $SSH_SERVER
              USER: $SSH_USER
              SSH_KEY: $SSH_KEY
              REMOTE_PATH: "/tmp/${BITBUCKET_REPO_SLUG}/${BITBUCKET_DEPLOYMENT_ENVIRONMENT}"
              LOCAL_PATH: 'dist'
          - pipe: atlassian/ssh-run:0.3.0
            variables:
              SERVER: $SSH_SERVER
              SSH_USER: $SSH_USER
              SSH_KEY: $SSH_KEY
              MODE: 'script'
              COMMAND: "scripts/deploy-${BITBUCKET_DEPLOYMENT_ENVIRONMENT}.sh"

pipelines:
  branches:
    development:
      - step:
          <<: *set-environment
          deployment: test
      - step: *build-app
      - step: *deploy-scp
