definitions:
  steps:
    - step: &set-environment
        name: Set environment
        script:
          - export > .env-ci-cd
          - cat .env-ci-cd
        artifacts:
          - .env-ci-cd
    - step: &test
        name: Test app
        image: node:14
        script:
          - npm i
          - npm t
    - step: &build
        name: Build app
        image: node:14
        script:
          - source .env-ci-cd
          - echo ${ENCODED_ENV_FILE} | base64 -d > .env
          - npm i
          - npm run build
        artifacts:
          - dist/**
    - step: &deploy-scp
        name: Deploy via SCP
        script:
          - source .env-ci-cd
          - pipe: atlassian/ssh-run:0.3.0
            variables:
              SERVER: $SSH_SERVER
              SSH_USER: $SSH_USER
              SSH_KEY: $SSH_KEY
              COMMAND: "mkdir -p /tmp/bns-dashboard/${BITBUCKET_DEPLOYMENT_ENVIRONMENT}/"
          - pipe: atlassian/scp-deploy:1.0.0
            variables:
              SERVER: $SSH_SERVER
              USER: $SSH_USER
              SSH_KEY: $SSH_KEY
              REMOTE_PATH: "/tmp/bns-dashboard/${BITBUCKET_DEPLOYMENT_ENVIRONMENT}/"
              LOCAL_PATH: 'dist'
          - pipe: atlassian/ssh-run:0.3.0
            variables:
              SERVER: $SSH_SERVER
              SSH_USER: $SSH_USER
              SSH_KEY: $SSH_KEY
              MODE: 'script'
              COMMAND: "scripts/deploy-${BITBUCKET_DEPLOYMENT_ENVIRONMENT}.sh"

pipelines:
  pull-requests:
    '{bugfix/*,feature/*,hotfix/*,release/*}':
    - step: *set-environment
    - parallel:
      - step: *test
      - step: *build
  branches:
    development:
      - step:
          <<: *set-environment
          deployment: test
      - parallel:
        - step: *test
        - step: *build
      - step: *deploy-scp
    staging:
      - step:
          <<: *set-environment
          deployment: staging
      - parallel:
        - step: *test
        - step: *build
      - step: *deploy-scp
    main:
      - step:
          <<: *set-environment
          deployment: production
      - parallel:
        - step: *test
        - step: *build
      - step: *deploy-scp
